{% set version = "1.1-9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sfsmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sfsmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sfsmisc/sfsmisc_{{ version }}.tar.gz
  sha256: d4df6cfd6287944bd59330004aee8b2891475ad2559850284e4edb3ef87af5e7

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('sfsmisc')"           # [not win]
    - "\"%R%\" -e \"library('sfsmisc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sfsmisc
  license: GPL (>= 2)
  summary: Useful utilities ['goodies'] from Seminar fuer Statistik ETH Zurich, some of which were ported from S-plus in the 1990's. For graphics, have pretty (Log-scale) axes, an enhanced Tukey-Anscombe plot, combining histogram and boxplot, 2d-residual plots, a 'tachoPlot()', pretty arrows, etc. For robustness, have a
    robust F test and robust range(). For system support, notably on Linux, provides 'Sys.*()' functions with more access to system and CPU information. Finally, miscellaneous utilities such as simple efficient prime numbers, integer codes, Duplicated(), toLatex.numeric() and is.whole().
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - sebastian-luna-valero

# Package: sfsmisc
# Title: Utilities from 'Seminar fuer Statistik' ETH Zurich
# Version: 1.1-4
# Date: 2019-04-25
# Authors@R: c(person("Martin","Maechler", role=c("aut","cre"), email="maechler@stat.math.ethz.ch", comment = c(ORCID = "0000-0002-8685-9910")) , person("Werner", "Stahel", role = "ctb", comment = "Functions: compresid2way(), f.robftest(), last(), p.scales(), p.dnorm()") , person("Andreas", "Ruckstuhl", role = "ctb", comment = "Functions: p.arrows(), p.profileTraces(), p.res.2x()") , person("Christian", "Keller", role = "ctb", comment = "Functions: histBxp(), p.tachoPlot()") , person("Kjetil", "Halvorsen", role = "ctb", comment = "Functions: KSd(), ecdf.ksCI()") , person("Alain", "Hauser", role = "ctb", comment = "Functions: cairoSwd(), is.whole(), toLatex.numeric()*") , person("Christoph", "Buser", role = "ctb", comment = "to function Duplicated()") , person("Lorenz", "Gygax", role = "ctb", comment = "to function p.res.2fact()") , person("Bill", "Venables", role = "ctb", comment = "Functions: empty.dimnames(), primes()") , person("Tony", "Plate", role = "ctb", comment = "to inv.seq()") # minor contributors: , person("Isabelle", "Fluckiger", role = "ctb") , person("Marcel", "Wolbers", role = "ctb") , person("Markus", "Keller", role = "ctb") , person("Sandrine", "Dudoit", role = "ctb") , person("Jane", "Fridlyand", role = "ctb") , person("Greg", "Snow", role = "ctb", comment = "to loessDemo()") , person("Henrik Aa.", "Nielsen", role = "ctb", comment = "to loessDemo()") , person("Vincent", "Carey", role = "ctb") , person("Ben", "Bolker", role = "ctb") , person("Philippe", "Grosjean", role = "ctb") , person("Frederic", "Ibanez", role = "ctb") , person("Caterina", "Savi", role = "ctb") , person("Charles", "Geyer", role = "ctb") , person("Jens", "Oehlschlagel", role = "ctb") )
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Description: Useful utilities ['goodies'] from Seminar fuer Statistik ETH Zurich, some of which were ported from S-plus in the 1990's. For graphics, have pretty (Log-scale) axes, an enhanced Tukey-Anscombe plot, combining histogram and boxplot, 2d-residual plots, a 'tachoPlot()', pretty arrows, etc. For robustness, have a robust F test and robust range(). For system support, notably on Linux, provides 'Sys.*()' functions with more access to system and CPU information. Finally, miscellaneous utilities such as simple efficient prime numbers, integer codes, Duplicated(), toLatex.numeric() and is.whole().
# Depends: R (>= 3.2.0)
# Imports: grDevices, methods, utils, stats
# Suggests: datasets, tcltk, cluster, lattice, MASS, Matrix, nlme, lokern
# Enhances: mgcv, rpart, nor1mix, polycor, sm, tikzDevice
# Encoding: latin1
# ByteCompile: yes
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2019-05-09 15:17:58 UTC; maechler
# Author: Martin Maechler [aut, cre] (<https://orcid.org/0000-0002-8685-9910>), Werner Stahel [ctb] (Functions: compresid2way(), f.robftest(), last(), p.scales(), p.dnorm()), Andreas Ruckstuhl [ctb] (Functions: p.arrows(), p.profileTraces(), p.res.2x()), Christian Keller [ctb] (Functions: histBxp(), p.tachoPlot()), Kjetil Halvorsen [ctb] (Functions: KSd(), ecdf.ksCI()), Alain Hauser [ctb] (Functions: cairoSwd(), is.whole(), toLatex.numeric()*), Christoph Buser [ctb] (to function Duplicated()), Lorenz Gygax [ctb] (to function p.res.2fact()), Bill Venables [ctb] (Functions: empty.dimnames(), primes()), Tony Plate [ctb] (to inv.seq()), Isabelle Fluckiger [ctb], Marcel Wolbers [ctb], Markus Keller [ctb], Sandrine Dudoit [ctb], Jane Fridlyand [ctb], Greg Snow [ctb] (to loessDemo()), Henrik Aa. Nielsen [ctb] (to loessDemo()), Vincent Carey [ctb], Ben Bolker [ctb], Philippe Grosjean [ctb], Frederic Ibanez [ctb], Caterina Savi [ctb], Charles Geyer [ctb], Jens Oehlschlagel [ctb]
# Repository: CRAN
# Date/Publication: 2019-05-11 07:40:02 UTC
