appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: vJJJiV4GfOkeLgssHt2V0h4iKxGMM3YDIFa2U6nCIUSLi28lYU0vYYYMh/nzGCACeVVs9oWlKBg9gU6P2hCR6gB/NSAtTEXCbOjPxsBYoLpPxMXpsHcPnwkTbiLfFb4esCaGRNjiqUppmiy1ArXcStderMKmw9ObRjR+lP+oTfgWBDXnTlM3dg58wFSWJvJW8zAEsSjl5kqfnkU1ugmXraQRWT5qlQ3IHvJSvP9mj/ebJevTlhtHr00xWUOKHQ54upFlXUtfOzLHEKSsXvvqujp1yrpLngySXW8MiAf0+t1dTakRtQ8dodnW3RY5aYU1drploq23OfJKQhb2iUaL7otqMNZBFxzlEbCYTpGfWRFIheB99Xeu7F2k44nDvPGyJr3Z/e5oL26+Wnk1Mc1Jiuo7TXI1ec1dNgndxxwql7gYqA9tWnc3KycacEScj2ITN5qVxdMexoJVyYGlJu1kBmUCYsqUiv/XqLNBIxJWtmcVd4XI/RYL70RuQKSXVqbIMskpNHdSO5JObQiV2fX4PpofVQrd3f2p/qDmSbbaLg76EjZGwLJIpXgNT2yjB5S9yEn61IdhB6keA1lQbM6O9yJa9QXkcnzI2JU6k5IcNHiZUFrESX0BVWUO4TFTs51NZoKn4yAnt88zAtV5aJP21/T37TRxT6tnW04KEOio0PM=
