travis:
  secure:
    BINSTAR_TOKEN: lhqGshGS8f0j6cPMNs88gi9RGq1zh61jHIxYCPVT8rwZX16ojpNFII/BWB8TqKlrHywhmlc04GeWv8QSDfNoGDrT7pOsUNQupoQpGQPKmnBzVgO7WhHVSNulkVezsgGJLHhBCHpEdm5QzkQ/Fm7q0m39xu3Xxw+REpPhDsujhNrFXMR6Tj9377ljSkAMyrbjocEieansE62UwQkaIH8RgqyImyI/wC7FDuBXMX0pMapNuYW7ToxGgCPKOAzZ3ZON2Z+huM+g781HJahIvLnHUouYcJVuDrSpGsQRnJhH+gcLrg6j9+YK4uuM5stIWxQPtv1sicvVxFehEwuNkdpS79c9Lf/H6M166uktAqRiuPL40DIWGn/8IY3IXYglCHwoYDODxTNsmP5WCTwK0oLkPlHQXhptLxZ33ftAUIdibRPDBAIxm/vokHmmxr2hrwlm1/k8V1FNrqUfBI0+uSXcFo6V/5w5dqTlSqNwBvn7PBfKI7XLpit+cWsY9/XKGi2m8Jp6cdWfitvYlAEO+JWs/H6UxxAjnVrVktlIjWBP1vNLVQHlW5HcXkA/bIKqnXXdOjwgDmvuxRI0huMoYMZTVdP42Ul7Bkz4/1qk7/AjdS3b9MQAajso8T7Y1wvpF6+BL7G+KtYaBbBkWlOxmOjJaWqyE3i6Zqgkj4wriWVnVVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
